Repository How-weather/front, pull requests merged in 2024-04, with the labels that each got.

#17 Chore: .eslintrc.js, .prettierrc.js
  .eslintrc.js
  .prettierrc.js
  package-lock.json
  package.json
Labels: ⚙ Setting

#22 Feat: CSS Tokens
  src/tokens/Colors.js
  src/tokens/Fonts.js
Labels: ⚙ Setting

#23 Refactor: Colors.js 토큰 추가
  src/tokens/Colors.js
Labels: ⚙ Setting, 🔨 Refactor

#28 Merge: dev to main
  public/cloudy.png
  public/gear.png
  public/here.png
  src/App.js
  src/components/header/index.js
  src/components/navbar/navbar.jsx
  src/components/navbar/navbarStyle.js
  src/components/weather/weather.jsx
  src/components/weather/weatherStyle.js
Labels: ✨ Feature

#29 Refactor: App.js에 있는 라우터 코드 index.js로 옮김 , Add: README.md, Refactor: .esLintrc.js React.props 타입 스킵 rule 추가
  README.md
  how-weather/package-lock.json
  src/index.js
Labels: ⚙ Setting, 🔨 Refactor

#31 feat: Space Token
  README.md
  src/tokens/Space.js
Labels: ✨ Feature

#33 Feat: intro, 404 Page, setting Page 마크업 스타일링, Refactor: Fonts token 추가
  public/images/남성.png
  public/images/여성.png
  src/App.js
  src/components/weather/weather.jsx
  src/layouts/recommendClothes/styled.jsx
  src/pages/intro/CheckIcon.jsx
  src/pages/intro/index.js
  src/pages/intro/index.jsx
  src/pages/intro/styled.js
  src/pages/main/index.jsx
  src/pages/notFound.js
  src/pages/recommend/index.jsx
  src/pages/setting/RadioBox.jsx
  src/pages/setting/index.js
  src/pages/setting/index.jsx
  src/pages/setting/styled.js
  src/tokens/Fonts.js
Labels: 🎨 Html&css, 🔨 Refactor

#35 feat: 시간별 날씨 기능
  package-lock.json
  package.json
  src/apis/axiosInstance.js
  src/apis/weatherApi.js
  src/components/box/styled.jsx
  src/components/card/styled.jsx
  src/components/text/styled.jsx
  src/components/text/textLink.jsx
  src/components/text/textP.jsx
  src/components/text/textSpan.jsx
  src/components/text/textStrong.jsx
  src/components/weather/weather.jsx
  src/components/weatherHour/styled.jsx
  src/components/weatherHour/weatherBar/styled.jsx
  src/components/weatherHour/weatherBar/weatherBar.jsx
  src/components/weatherHour/weatherHour.jsx
  src/components/weatherHour/weatherImage/styled.jsx
  src/components/weatherHour/weatherImage/weatherImage.jsx
  src/components/weatherHour/weatherTemp/styled.jsx
  src/components/weatherHour/weatherTemp/weatherTemp.jsx
  src/layouts/recommendClothes/recommendClothes.jsx
  src/layouts/recommendClothes/styled.jsx
  src/layouts/weatherTime/styled.jsx
  src/layouts/weatherTime/weatherTime.jsx
  src/pages/main/index.jsx
  src/utils/constant.js
Labels: ✨ Feature

#36 feat: 오늘의 날씨 추가
  src/components/layout/style.js
  src/components/weather/weather.jsx
  src/components/weather/weatherStyle.js
  src/pages/main/index.jsx
Labels: ✨ Feature

#38 Dev
  package-lock.json
  package.json
  src/components/header/index.js
  src/components/navbar/navbar.jsx
  src/components/navbar/navbarStyle.js
  src/components/weather/weatherAPI.jsx
Labels: ✨ Feature, 🎨 Html&css

#37 Add: Vercel / Feat: Vercel 배포 / Refactor: Intro, Setting page 마크업 및 스타일링
  .gitignore
  package-lock.json
  package.json
  src/components/RadioBox/RadioBox.jsx
  src/components/SubmitBox/SubmitBox.jsx
  src/components/header/index.js
  src/index.js
  src/pages/intro/CheckIcon.jsx
  src/pages/intro/index.jsx
  src/pages/intro/styled.js
  src/pages/setting/index.jsx
  src/pages/setting/styled.js
Labels: ⚙ Setting, 🌏 Deploy, 🔨 Refactor

#41 Codinator page
  package-lock.json
  package.json
  public/images/shop_29.png
  public/images/shop_mu.png
  public/images/shop_new.png
  public/images/shop_zi.png
  src/pages/recommend/asdf.css
  src/pages/recommend/codiData.js
  src/pages/recommend/index.js
  src/pages/recommend/index.jsx
  src/pages/recommend/style.js
Labels: ✨ Feature, 🎨 Html&css

#43 Refactor, Feat : 이미지, 시간별 날씨
  package-lock.json
  package.json
  public/data/mock.json
  src/apis/axiosInstance.js
  src/apis/weatherApi.js
  src/components/box/boxAccessory.jsx
  src/components/card/cardItem.jsx
  src/components/weatherHour/styled.jsx
  src/components/weatherHour/weatherBar/styled.jsx
  src/components/weatherHour/weatherBar/weatherBar.jsx
  src/components/weatherHour/weatherHour.jsx
  src/components/weatherHour/weatherImage/styled.jsx
  src/components/weatherHour/weatherImage/weatherImage.jsx
  src/components/weatherHour/weatherTemp/styled.jsx
  src/components/weatherHour/weatherTemp/weatherTemp.jsx
  src/layouts/recommendClothes/recommendClothes.jsx
  src/layouts/weatherTime/styled.jsx
  src/layouts/weatherTime/weatherTime.jsx
  src/pages/main/index.jsx
  src/utils/constant.js
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix

#44 Refactor: 이미지 한글 > 영문으로 수정
  package-lock.json
  public/images/cloud.svg
  public/images/littlecloud.svg
  public/images/mask.svg
  public/images/outer.svg
  public/images/outerw.svg
  public/images/pants.svg
  public/images/pantsw.svg
  public/images/rain.svg
  public/images/shirt.svg
  public/images/shirtw.svg
  public/images/snow.svg
  public/images/sun.svg
  src/pages/main/index.js
  src/utils/constant.js
Labels: 🎨 Html&css, 🔨 Refactor

#48 "feat: setting localStorage"
  package.json
  src/components/BottomSheet/BottomSheet.jsx
  src/components/BottomSheet/styled.js
  src/components/BottomSheet/weekWeather.js
  src/components/RadioBox/RadioBox.jsx
  src/pages/intro/index.jsx
  src/pages/main/index.jsx
  src/pages/setting/index.jsx
Labels: ✨ Feature, 🔨 Refactor

#51 Feat: 인트로와 설정 localstorage 적용
  public/data/mock.json
  src/components/BottomSheet/BottomSheet.jsx
  src/layouts/recommendClothes/recommendClothes.jsx
  src/layouts/weatherTime/weatherTime.jsx
  src/pages/main/index.js
  src/pages/main/index.jsx
  src/utils/constant.js
Labels: ✨ Feature

#52 Add: favicon.png
  public/favicon.png
  public/index.html
  public/logo192.png
  public/logo512.png
Labels: ⚙ Setting

#54 Dev
  README.md
  src/components/BottomSheet/styled.js
  src/components/layout/index.js
  src/pages/recommend/style.js
Labels: 🎨 Html&css, 📃 Docs, 🔨 Refactor

#55 데브에서 메인으로 머지
  README.md
  src/components/BottomSheet/styled.js
  src/components/layout/index.js
  src/pages/recommend/style.js
Labels: 🌏 Deploy

#58 bug: sdsd 텍스트 나오는 것 수정
  src/layouts/weatherTime/weatherTime.jsx
Labels: 🐞 BugFix
